project:
  name: unc-img-laplace
  experiment: diag

training:
  batch_size: 256
  epochs: 2
  lr: 0.001
  margin: 1
  distance: LpDistance
  loss: ContrastiveLoss
  reducer: AvgNonZero
  miner: BatchEasyHardMiner

wandb: 358da8cfb93c05b5d6d342a84fc027188f27e79a