project:
  name: unc-img-laplace
  experiment: diag

training:
  batch_size: 256
  epochs: 10
  lr: 0.01
  margin: 0.2
  distance: LpDistance
  loss: ContrastiveLoss #Triplet
  reducer: AvgNonZero
  miner: BatchEasyHardMiner #TripletMarginMiner

wandb: 358da8cfb93c05b5d6d342a84fc027188f27e79a