project:
  name: unc-img-laplace
  experiment: exp-1

training:
  batch_size: 64
  epochs: 1
  lr: 0.01
  margin: 0.8
  distance: LpDistance
  loss: Triplet

wandb: 358da8cfb93c05b5d6d342a84fc027188f27e79a